#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <remote_keyboard_icons.h>

int32_t remote_keyboard_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm remote_keyboard!");

    return 0;
}
