#include <gui/gui.h>
#include <gui/view_dispatcher.h>
#include <input/input.h>
#include "../remote_keyboard.h"
#include "../include/gui.h"
/* generated by fbt from .png files in images folder */
#include <remote_keyboard_icons.h>

static GuiConStatus stat_conn = {"Connected", 10};
static GuiConStatus stat_no_conn = {"No Conn", 18};

static void app_draw_scene_callback(Canvas* canvas, void* ctx) {
    RemoteKbApp* app = ctx; // context is what is send to the drawer
    UNUSED(app);

    GuiConStatus usb_stat = (app->state.usb_connected) ? stat_conn : stat_no_conn;
    GuiConStatus bt_stat = (app->state.bt_connected == BtStatusConnected) ? stat_conn : stat_no_conn;

    canvas_clear(canvas);
    canvas_draw_icon(canvas, 80, 8, &I_bluetooth); // bluetooth icon
    canvas_draw_icon(canvas, 48, 8, &I_arrow); // arrow icon
    canvas_draw_icon(canvas, 16, 8, &I_usb); // usb icon
    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str(canvas, 0 + usb_stat.offset, 48, usb_stat.str); // usb connection status
    canvas_draw_str(canvas, 64 + bt_stat.offset, 48, bt_stat.str); // bluetooth connection status
}

static void app_input_callback(InputEvent* input_event, void* ctx) {
    furi_assert(ctx);

    FuriMessageQueue* event_queue = ctx;
    furi_message_queue_put(event_queue, input_event, FuriWaitForever);
}

int32_t gui_process(void* p) {
    RemoteKbApp* app = p;

    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, app_draw_scene_callback, app);
    view_port_input_callback_set(view_port, app_input_callback, event_queue);

    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    InputEvent event;
    bool running = true;
    while(running) {
        if(furi_message_queue_get(event_queue, &event, 100) == FuriStatusOk) {
            if((event.type == InputTypePress) || (event.type == InputTypeRepeat)) {
                switch(event.key) {
                case InputKeyUp:
                    queue_in_buffer(app->kb_buffer, 'f');
                    break;
                case InputKeyBack:
                    running = false;
                    break;
                default:
                    break;
                }
            }
        }
        view_port_update(view_port);
    }

    view_port_enabled_set(view_port, false);
    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    furi_message_queue_free(event_queue);

    //free view dispatcher
    furi_record_close(RECORD_GUI);

    return 0;
}
